version: "2"
linters:
  enable:
    - errorlint
    - misspell
    - unconvert
    - unparam
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
      - testdata$
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kova-land/extension-sdk-go
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - testdata$
